version: "3.7"

services:

#FOR MySQL Support : 
# mariadb:
#  image: "mariadb"
#  container_name: "mariadb"
#  hostname: "mariadb"
#  restart: always
#  env_file:
#   - "./cfg/.env"
#  volumes:
#   - "mariadb_vol:/var/lib/mysql"
#   - "/etc/localtime:/etc/localtime:ro"
#  environment:
#   - "MYSQL_ROOT_PASSWORD=<my-secret-pw>"
#   - "MYSQL_PASSWORD=<mysql_user_password"
#   - "MYSQL_DATABASE=privatebin"
#   - "MYSQL_USER=<mysql_user>"



  privatebin:
    image: privatebin/nginx-fpm-alpine:latest #TAGS stable latest edge nightly 
    read_only: true # not in compose 3.0 documentation but appears supported 
    user: 1001
    #used to force the user used to run PrivateBin (refer to docker documentation)
    #Docker uses user 1000 by default
    #to find your user uid run : id -u <username>
    #replace 1001 by YOUR USER id, if different.
    volumes:
      - './privatebin-data:/srv/data' # data volume for pastes allows pastes
      # to persist after container stop or restart
      - './cfg/conf.php:/srv/cfg/conf.php:ro' # second volume for custom configuration file - read-only
    ports:
      # To update: Be sure to use a reverse proxy for HTTPS termination 
      # in front of it for production environments.
      # ie, The Nginx setup supports only HTTP, so make sure that you run 
      # another webserver as reverse proxy in front of this for HTTPS 
      #offloading and reducing the attack surface on your TLS stack. The 
      # Nginx in this image is set up to deflate/gzip text content.
      - 8080:8080
    restart: unless-stopped
